name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Mody9156   # ton pseudo GitHub

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: custom       # branche où sera poussé le fichier
          build_dir: dist             # contenu local de dist/ sera poussé
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
